### ISSUE TITLE
Documentation for Checkbox has no info about cols and renderType

### ISSUE THREAD

**Issue by PKuhlmay** [FriendsOfTYPO3/content-blocks#11]
The documentation for the Checkbox has some information about the properties `default` and `items`, but no one for `cols` and `renderType`.

For `cols` you could describe, that this is the number of cols, in which the checkboxes will be displayed. This is not obvious to everybody.

For `renderType` you could list all the available renderTypes which are shipped by the core. See: https://docs.typo3.org/m/typo3/reference-tca/main/en-us/ColumnsConfig/Type/Check/Index.html#columns-check

BTW I get an error when using the `checkboxLabeledToggle`:
`PHP Warning: Undefined array key 0 in /var/www/html/vendor/typo3/cms-backend/Classes/Form/Element/CheckboxLabeledToggleElement.php line 176` 
This comes from the core but I am not sure yet if it is related to content blocks.
If checkboxLabeledToggle doesn't work with content blocks yet, the documentation should also list this value as not allowed.

**Comment by nhovratov** [comment]
1. We didn't document every single configuration option, because this would just duplicate the TCA documentation. Rather we try to showcase what is needed 99% of the time.
2. Your error: Yes, this looks like a core bug. But: When you use checkboxLabeledToggle, you should at least define one item with labelChecked and labelUnchecked.
