### ISSUE TITLE
Collection sorting

### ISSUE THREAD

**Issue by ogrosko** [FriendsOfTYPO3/content-blocks#110]
Hello @nhovratov, 
we’ve encountered a problem with a collection sorting. We have an element with a collection like this:

```
-
    identifier: slides
    type: Collection
    labelField: title
```

Using Extbase model for this element with slides, it gave us wrong order of slides. Adding `foreign_sortby: sorting` didn’t help.
Workaround which work for us is adding following config to `TCA/Overrides/tt_content.php`

```
'slides' => [
    'config' => [
        'foreign_sortby' => 'sorting',
    ],
], 
```

**Comment by nhovratov** [comment]
Answer already posted in Slack:

> Ah, probably because it is set in columnsOverrides . This needs to be fixed in Content Blocks then.
I haven't have tested with Extbase much, so it is expected that some problems might occur like this.
There are probably other fields which are evaluated in Extbase without taking columnsOverrides into account.

**Comment by devskio** [comment]
@nhovratov shouldn't be `foreign_sortby => sorting` added automatically if sorting of Collection is enabled?

**Comment by nhovratov** [comment]
@devskio Not sure what you mean. `foreign_sortby` is only used for relations to external tables, so that it is possible to override their sorting depending on the parent. This is an extra opt-in, if sorting should differ to the local one. The option `sortable` does only set `sortby => sorting` for the local table.
