### ISSUE TITLE
[STRUCTURE] Content Elements, Record-Types and Page Types

### ISSUE THREAD

**Issue by benjaminkott** [FriendsOfTYPO3/content-blocks#141]
We agreed a while ago to move the wording from "Content Elements" towards "Content Blocks" to match other systems. We are now introducing "Content Elements" again as a "Content Blocks" subtype. This is a major problem since we already started communicating about content blocks as a replacement for content elements.

While I value and find it helpful to also allow the wizard/cli command to create more kinds of records.

Page types are in no way any subtype of content blocks. They are simply page types. If we agree to also have a generator for these, they need to be on the same level as Content Blocks by their definition.

Record types are another problem because they are per definition and core handling not types. But simply records. We only use the type for sub-classing records. We have the same problem here as we have with page types, they are not a subtype of Content Blocks.

![image](https://github.com/nhovratov/content-blocks/assets/3243119/02609b7b-ba8c-4a29-b6aa-d7245ae72ab3)

**Comment by nhovratov** [comment]
Well, this is a matter of definition. In order to support Page Types and Record Types we needed to make the term "Content Block" more general. Have a look at the terminology: https://docs.typo3.org/p/contentblocks/content-blocks/main/en-us/Introduction/Index.html#terminology

We can of course rename things again, but I would do this (if at all) in the Core patch. We are in a very late stage of the project for introducing bigger breaking changes.

**Comment by nhovratov** [comment]
Content Blocks is more than a Content Element builder now. This is a whole API around Content Types in which Content Elements and Page Types are just special cases.

**Comment by nhovratov** [comment]
The structure will be tackled in the Core patch, but will be kept in this extension.
