### ISSUE TITLE
Extension not installable in non composer installations

### ISSUE THREAD

**Issue by mkrappitz** [FriendsOfTYPO3/content-blocks#23]
Installation fails for me in a 12.4.6 TYPO3 installation with only EXT:container and my provider extension installed besides. The error message is:
"Expected to find class "TYPO3\CMS\ContentBlocks\Backend\Preview\PreviewRenderer" in file "/.../typo3conf/ext/content_blocks/Classes/Backend/Preview/PreviewRenderer.php" while importing services from resource "../Classes/*", but it was not found! Check the namespace prefix used with the resource."
The file exists in this path. Without investigating further, I would guess that TYPO3 core in non composer installations has a class loading problem with the TYPO3\CMS vendorname in a non system extension.

**Comment by nhovratov** [comment]
@mkrappitz Many thanks for reporting the issue! Yes, indeed the composer type `typo3-cms-framework` seems to disable psr-4 autoload in classic mode. Probably because this is pre-processed for core extensions. It's now fixed by changing it to `typo3-cms-extension`. The TYPO3\CMS vendor seems to do no harm though.

**Comment by mkrappitz** [comment]
Thanks a lot for this quick fix! Works now!
