### ISSUE TITLE
Cant change icon when creating contentelement with skeleton command

### ISSUE THREAD

**Issue by jramke** [FriendsOfTYPO3/content-blocks#25]
Hey, 

i encounter a cache bug where I cant change the default icon after creating a contentelement skeleton with the `make:content-block` command.

Tried `ddev typo3 cache:flush -g system`, `ddev typo3 cache:flush`, the lightning icon in the backend, flush cache via maintance module and tried to remove temporary assets (if existing) there too, but nothing seems to work.

If I open the symlinked public path to the icon (https://content-blocks.ddev.site/_assets/cb/myvendor/myelement/Icon.svg) and make a hard refresh in the browser and go through the steps again it works sometimes in the page and detail view but never in the contentelement create wizard.

Unfortunately i currently couldnt reproduce it more reliable.
Issue arises in clone of this repo and also on a v12.4.6 composer test site.

**Comment by nhovratov** [comment]
Hey @jramke, first of all thanks for testing out Content Blocks!

I've encountered your issue already. The problem is that TYPO3 caches icon markup in the local storage of your browser. So it doesn't matter how many times you flush the TYPO3 caches. You need to delete the local storage cache via dev tools.

Maybe Content Blocks should generate another icon identifier from the md5 hash of the icon or something.

**Comment by jramke** [comment]
Hey, thanks for the fast response.

Oh, that is really good to know. 

Yeah something like that is maybe a good idea.

**Comment by nhovratov** [comment]
Fixed in 0.1.3
