### ISSUE TITLE
Option to hide PageType in NewPageDragArea

### ISSUE THREAD

**Issue by maikschneider** [FriendsOfTYPO3/content-blocks#253]
For reasons of constancy, I added a dedicated PageType for every kind page. However, I do not want to have every page as drag item in the toolbar menu of the page tree (e.g. Homepage). 

It would be nice to have a configuration option in the `EditorInterface.yaml` to disable the hardcoded include in [ServiceProvider](https://github.com/nhovratov/content-blocks/blob/main/Classes/ServiceProvider.php#L204).

**Comment by nhovratov** [comment]
Hi, yes I encountered this myself when I also had a "Homepage" page type. I'm not sure whether this should be an option in the yaml file. If so, this should apply for all types, not only pages. My suggestion would be to hide it via user tsconfig. Unfortunately, I think this is not possible in v12. In v13 there is a new Event, so that you can override it with your global user.tsconfig file.

**Comment by nhovratov** [comment]
This works in v13:

Configuration/user.tsconfig

```
options {
  pageTree {
    # remove page type "Homepage"
    doktypesToShowInNewPageDragArea := removeFromList(1698230862)
  }
}
```

**Comment by nhovratov** [comment]
Will add it to documentation.
