### ISSUE TITLE
[FEATURE] Bundle AssetCollector CSS files

### ISSUE THREAD

**Issue by fe-hicking** [FriendsOfTYPO3/content-blocks#32]
Theoretically it could/should be possible via an AssetCollector "writeJavascriptToTemporaryFile" (within Core) to bundle all generated assets instead of having individual CSS HTTP requests.

(I'll offer to look into this, just wanted to write this down)

**Comment by jonaseberle** [comment]
Do you mean as a default for content blocks?

Btw I don't think we have to reduce requests any more with HTTP/2.

**Comment by fe-hicking** [comment]
More context: This came up during the T3CRR workshop that Nikita held.

If many content elements are contained this could lead to a more
cluttered queue of files. 

Personally I'd argue for it to be optional/configurable. Maxbe content-blocks could try to use a sitesetting to toggle the behavior; guess it can't easily access a config.removeDefaultJS=external TypoScript setting?

I believe SEO tools sometimes still recommend fewer requests, so IMO having such an option would be a valid wish? But that's up to discussion of course, I was just triggered by "would it be possible". 😊

**Comment by nhovratov** [comment]
If we do this, it should align we the possibilities of the standard AssetCollectors. So it should be made a Core features first. See issues: https://forge.typo3.org/issues/91312, https://forge.typo3.org/issues/93511

**Comment by kaesetoast** [comment]
@jonaseberle it actually still is a recommended practice, since there are more factors at play. Harry Roberts recently wrote about this: https://csswizardry.com/2023/10/the-three-c-concatenate-compress-cache/

This is the one bad feeling I had when I initially installed the extension. The asset ViewHelpers brought back some bad feelings I had in when I first started with TYPO3. The team back then had written ViewHelpers to include CSS and JavaScript files from within Fluid templates and partials. The reasoning was that on a page that does not have an accordion, I do not need to ship the accordion CSS. This created two problems:

- Performance: You either end up with a lot of requests (which was worse back then, but http/2 does not seem to solve this the way we thought), or if you used sth. like the `scriptmerger` extension, you ended up with a giant bundles that were different for each page. Wich effectiveley broke the advantages of caching.
- Maintenance: Since there was no way of knowing where CSS might come from (since there was no central place that included files) this was incredibly hard to maintain. There were side-effects all over the place, which were not even consistent from page to page.

Right now I'm using `content_blocks` without the asset ViewHelpers at all. And while I like the idea of having independent blocks that can be moved from project to project, specifically the CSS part gives me some headaches. In order for this to work, you need a consistent class-nomenclature, maybe usage of custom properties that the main framework provides, etc. Right now this feels a bit like a footgun. If I want to use a block that enques its own CSS, I probably have to either add CSS overrides, which generally sucks, or I have to override the template, which kinda defeats the purpose of having a pluggable block.

---

Sorry for the kind of bloated reply. Long story short: I think in order for the asset ViewHelpers to be useful, they definitely should write to a global asset bundle and avoid making additional requests. So +1 for that.
Regarding the rest: Happy to move this discussion elsewhere, but I feel like this might be an important one to have.

**Comment by jonaseberle** [comment]
We don't have a perfect solution but I also cannot say what TYPO3 could do better...

External build processes that are able to bundle are necessary in my opinion.
For me TYPO3 cannot usefully help with minifying or concatenating because I want to use TypeScript, babel, SCSS or browserslist anyways and I don't trust any PHP solution in that domain ;)
I point the AssetCollector ViewHelpers at the built artifacts then. This is useful for asset-heavy components that are not used on any page. Bundlers with multiple entry points are perfect for re-using code parts for JavaScript – for CSS not so much yet (until we have `import()`). 
I am experimenting with CSS-as-JavaScript to leverage that for CSS as well and it works well especially when working with Web Components.
Also AssetCollector's "only include assets with the same identifier once" is helpful, especially for CSS – that way you don't have to have entry points for each component but you can have a group of components use the same assets.

Anyways, IMHO it's not a topic for the Content Blocks but about Core's `AssetCollector`. It's up to the core or an extension to implement minifying/concatenating. [EXT:min](https://extensions.typo3.org/extension/min) should be able to do that.

**Comment by baschny** [comment]
I stumbled over this discussion, very interesting! My point of view.

A) Assets being serving as a potential feature of content blocks

I think this is a good idea. There are different valid use-cases:

1. Integrations with their own frontend build stacks (mostly in agencies), so having a way to "turn off" asset collection is needed (it still might be good to be able to have the CSS/SASS files alongside the content blocks, just don't have them processed by TYPO3)
2. On the other hand TYPO3 should also cope for the "newcomer" which just wants to make a small site, and thus would be happy to be able to put the CSS files in the content blocks folder and "it just works"!

Use-case 2 doesn't need to be very fancy or smart, simply add all assets from all content blocks to the main page asset collector and apply the configured post processing (concatenate etc) on them. It does not even have to be via the fluid asset view helper. Simply have a file name convention a "styles.css" and "main.js"  placed somewhere in the content blocks folder structure, and it gets attached in the frontend rendering process.

B) HTTP/2

It's 2024 and apparently only around 30% of websites are serving with HTTP/2 (source https://w3techs.com/technologies/details/ce-http2). The misleading stats from the other articles deal with browser support (all major browsers nowadays support HTTP/2, so if you *have* a HTTP/2 site, of course the usage rate of HTTP/2 will be much larger).

Of course newer TYPO3 should be prepared for the future, but the concatenated feature is still required for "most" regular hosting environments we have out there.

**Comment by jonaseberle** [comment]
Hi Ernesto,

thank you for the input.
It is an interesting idea to have implicit loading. (It should be `frontend`/`backend`.css/js then IMHO because the backend previews are an integral part of ContentBlocks that we deem important for the editor experience). 
We are currently in feature freeze because we are in review with the Core patch and it is not yet clear which of the current features will get in but I added this to our team's list and we will discuss it.

**Regarding the original post (missing concatenation):**
As Nikita commented already: Our `<cb:asset.css>` ViewHelper just registers the CSS with `AssetCollector` but its `AssetRenderer` does not work yet with the existing `config.concatenateCss/Js`. That is a missing feature but that needs to be tackled in Core (https://forge.typo3.org/issues/91312) and it would make a mess IMHO if we would try to work around it. `AssetCollector` is the more modern API so we'll stick to it.

It is really an interesting topic and we are very interested in best practices for JS/CSS handling in TYPO3 sites but the original issue will be solved automagically when Core solves it and we went a bit off-topic with the rest ;) I'll close here.
