### ISSUE TITLE
[FEATURE] Add option to prefix fields with vendor name only

### ISSUE THREAD

**Issue by greenfieldr** [FriendsOfTYPO3/content-blocks#37]
As part of the first real-life project with Content Blocks , I quickly came to the point where I created new fields for content elements that I would like to use across several content elements (e.g. a dropdown for selecting icons). 

In general I like the concept of a prefix on fields in order to maintain a clear overview of where fields belong to and to avoid conflicts in principle resp. to minimize the chance of those.
 
This gave me the idea and question of whether an option "prefixWithVendorNameOnly" could be useful in addition to the existing prefixFields option, so that you don't have to prefix each field manually while still have a uniform prefix for all fields within a vendor. 

Just an idea, maybe totally nonsense on closer examination, but I still wanted to at least throw the idea out there, in case I'm not the only one who sees this as a useful feature. Maybe there's another, better way to handle these use-cases. If so, please let me know. If so I could also help with some documentation for it, if missing. 

As always: don't hesitate to give me a ping if you've further questions or I can help with implementing the feature if it comes into consideration. 

Best regards,
Marcel

**Comment by nhovratov** [comment]
Hi Marcel, funnily I had the same idea yesterday while working on a customer project. I also wanted to reuse some fields and had to prefix them manually with the vendor. This forced me to change all templates, where the field was used.

However, I'm not sure if this is worth an option and the increased complexity. Everytime you want to share a field, you can set `prefixField: false` directly for the field. This overrules the global option `prefixFields`. Of couse, you need to know beforehand, if you want to share a field. Otherwise, you have to migrate the database field.

I will think about such a feature when I have time. For own new projects a vendor prefix would be enough and would enable to easily share fields across content blocks without the need to migrate later on.

**Comment by greenfieldr** [comment]
For sure, this is just one perspective on how to handle this, but maybe it helps understanding my intention about this feature request. 

To minimize extra fields and prevent unnecessarily increasing the horizontal size of database tables, we already try to reuse semantically suitable fields as much as possible, regardless if built natively or with content blocks. 
Using Content Blocks we'd most likely always disable prefixes to keep this flexibility of reusing fields directly or in the future without need for migration steps, which also need to be integrated in the deployment processes. 

So just from our perspective all fields would get a manual prefix along with the vendor name which would be either our company name or a project specific one.

**Comment by garvinhicking** [comment]
I understand that this feature might create flood of config item keys, so maybe 'prefixField' could be changed to a tri-state: true, false, 'vendor'? We'd be happy to implement this, if at some point you decide it's ok to have it. :-)

**Comment by nhovratov** [comment]
Yes, I had the same idea with the three values. I would really appreciate help there. Do you want to have a call with me, so I can show you the architecture?
