### ISSUE TITLE
[DOC] TYPO3/Seo mixin is not documented, and maybe others too

### ISSUE THREAD

**Issue by PKuhlmay** [FriendsOfTYPO3/content-blocks#47]
The basic "TYPO3/Seo" seems not to be documented at the moment: https://docs.typo3.org/p/contentblocks/content-blocks/main/en-us/IntegratorManual/Basics/Index.html

This basic is already in version 0.1.6, I tried it and it worked.

Only these are documented:
TYPO3/Appearance
TYPO3/Links
TYPO3/Categories

There might be others which are not documented but already shipped with the extension.

**Comment by nhovratov** [comment]
@PKuhlmay Thanks for opening the issue! There were no other undocumented standard Basics. I've added the Seo Basic quickly, because I needed it in my project and thus I didn't document it.

As we discussed on Slack, the Seo Tab is now automatically added, when the seo extension is loaded. This behaves exactly the same as with the standard page type "1". In addition, the meta tab is now also added. It has only description and keywords. Description will be removed from TYPO3, if the seo extension is loaded. So then there is only keywords. This field is only used for TYPO3 keywords menu and in some fluid_styled_content elements. But because it has core usage, I kept it nevertheless.

About the notes tab: I've added it, because it is a core functionality, built in the page type itself. It should thus be available for all page types automatically. I think there is no harm in displaying it.
