### ISSUE TITLE
Cannot use global partial in Content Block with f:render

### ISSUE THREAD

**Issue by nilkra** [FriendsOfTYPO3/content-blocks#55]
If i try to use a global Partial from the "packages/extension/Resources/Private/Partials/Page" directory, i get the following error:

![error](https://github.com/nhovratov/content-blocks/assets/77601065/6c3727b1-c7e3-4ecc-a900-d6f242d57c1f)

I am trying to implement the partial with the following code:
```
<f:render section="ShoppingCart" partial="ShoppingCart" arguments="{_all}" />
```
Is there a way to achieve my goal?

**Comment by nhovratov** [comment]
First of all: We don't recommend using global partials, as this adds dependencies for your Content Block.
That said, in order to make your extension Partials available in Content Blocks, you have to add the partialRootPaths in TypoScript:

`lib.contentBlock.partialRootPaths.200 = EXT:test/Resources/Private/Partials/Page/`

**Comment by nhovratov** [comment]
This is now documented here: https://docs.typo3.org/p/contentblocks/content-blocks/main/en-us/Guides/SharedPartials/Index.html
