### ISSUE TITLE
Unable to Flush the Cache through the TYPO3 Backend after ContentBlock Folder Deletion

### ISSUE THREAD

**Issue by filippos-gmk** [FriendsOfTYPO3/content-blocks#64]
Hello, 

I noticed that after deleting the entire folder of a content block I wanted to remove from the System, it is impossible to access the Backend in order to flush the cache and get the System running again. It has to be done either over the CLI or the Install Tool. A folder deletion could therefore torpedo an entire system if casually done over rsync.

![Bildschirmfoto 2023-12-14 um 13 01 23](https://github.com/nhovratov/content-blocks/assets/103989063/ba1e61a0-104c-4a60-8932-185188d8795b)

**Comment by nhovratov** [comment]
The problem is that all Content Blocks are cached. The cache doesn't know about your manual deletion of a Content Block. I don't see this as an actual issue. If you want to get rid of a content block, you will consequently have access to the TYPO3 instance either via FTP or SSH. So you always can delete the cache via `typo3 cache:flush` or by deleting the var/cache folder. The GUI could also invalidate the cache when you delete it there.

**Comment by krausandre** [comment]
I want to add that the CLI is not your best friend, especially when you are a newbie or a frontend dev. And the GUI shouldn't be installed in production for "normal" cases.

Edit: I would also say, since the error message tells you to flush system cache, (what is a usefull info by the way), it should be possible to flush the cache. It is not a good user experience, if the system is broken this hard, every time you want to get rid of a content block.

**Comment by nhovratov** [comment]
Okay, I removed the exception. You are right, after some thoughts it is truly a bad user experience not being able to flush the cache in the backend, after deleting a Content Block. But be aware that this creates a buggy state as long as the caches are not flushed!
