### ISSUE TITLE
AssetsCollector for backend (EditorPreview.html) do not add cache buster

### ISSUE THREAD

**Issue by kszymukowicz** [FriendsOfTYPO3/content-blocks#79]
When I add css in `EditorPreview.html` with `cb:asset.css` the css file is added but it has no cache buster. 
On `Frontend.html` everything works as expected and cache buster is added.

**Comment by jonaseberle** [comment]
Thank you!
I see that also `f:asset.css` does not add the `?<timestamp>` cache-buster to the URL in the backend. (It was added for the frontend in https://forge.typo3.org/issues/91889)

I wonder if that is because of this condition https://github.com/TYPO3/typo3/blob/main/typo3/sysext/core/Classes/Page/AssetRenderer.php#L119-L121

**Comment by jonaseberle** [comment]
It was not that condition but

`GeneralUtility::createVersionNumberedFilename($file)` thinks the file does not exist
https://github.com/TYPO3/typo3/blob/main/typo3/sysext/core/Classes/Utility/GeneralUtility.php#L2035-L2037
![image](https://github.com/nhovratov/content-blocks/assets/1678001/8b508402-ab81-4288-b7cb-c2b3fdb8b8d7).

I think that might be a bug for AssetCollector assets in the backend?

**Comment by nhovratov** [comment]
This might be fixed with https://review.typo3.org/c/Packages/TYPO3.CMS/+/77018
We also do not use custom asset ViewHelpers anymore in v13, so I'll close this issue :)
